name: PHP Lambda CI/CD Deployment

on:
  push:
    branches:
      - master

env:
  PULUMI_STACK_NAME: prod
  ARTIFACT_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
  # Define the version key based on the Git short SHA for uniqueness
  # This corresponds to the 'codeVersionKey' Pulumi config setting
  CODE_VERSION_KEY: ${{ github.sha }}/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- AWS AUTHENTICATION ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup PHP (required for Bref/Composer)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Must match your Bref layer version
          extensions: mbstring, json
          coverage: none

      - name: Install Composer Dependencies (if using shared code)
        run: composer install --prefer-dist --no-dev --no-suggest

      - name: Prepare Lambda Deployment Packages
        run: |
          # 1. Package the login Lambda
          # copy the handler and Composer vendor files into tmp build dir
          mkdir -p ./.build/login
          cp src/auth/login/index.php ./.build/login/
          # Bref requires vendor dir at root
          cp -r vendor ./.build/login/vendor
          zip -r login.zip ./.build/login -x '*/\.*'
          
          mkdir -p ./.build/logout
          cp src/auth/logout/index.php ./.build/logout/
          cp -r vendor ./.build/logout/vendor
          zip -r logout.zip ./.build/logout -x '*/\.*'
      
      - name: Upload Artifacts to S3
        run: |
          # Upload them to the versioned S3 ting
          aws s3 cp login.zip s3://${{ env.ARTIFACT_BUCKET }}/${{ env.CODE_VERSION_KEY }}/login.zip
          aws s3 cp logout.zip s3://${{ env.ARTIFACT_BUCKET }}/${{ env.CODE_VERSION_KEY }}/logout.zip
